FROM alpine/git AS downloader
WORKDIR /
RUN git clone https://github.com/snailyp/gemini-balance.git

WORKDIR /gemini-balance
RUN cp .env.example .env && \
    sed -i 's/DATABASE_TYPE=mysql/DATABASE_TYPE=sqlite/' .env && \
    sed -i 's/#SQLITE_DATABASE=default_db/SQLITE_DATABASE=default_db/' .env

FROM python:slim

RUN apt-get update && apt-get install -y curl && \
    curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && \
    dpkg -i cloudflared.deb && \
    apt-get clean && rm -f cloudflared.deb

WORKDIR /app

COPY --from=downloader /gemini-balance /app

RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
